
services:
  redis:
    container_name: quote_editor_redis
    image: redis:7.2.4-alpine
    expose:
      - 6379
    ports:
      - "6379:6379"
    networks:
      - quote_editor_network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 20s
      retries: 100

networks:
  quote_editor_network:
    name: quote_editor_network
